# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20181017_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='List',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lists.List'),
        ),
    ]
