# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20181017_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='List',
        ),
        migrations.AddField(
            model_name='item',
            name='list',
            field=models.TextField(default=''),
        ),
    ]
